# Generated by Django 5.0.6 on 2024-09-23 21:25

import django.db.models.deletion
import shop.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=300, verbose_name='Название')),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('is_show', models.BooleanField(db_index=True, default=True, verbose_name='Показывать на сайте')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=300, verbose_name='Значение')),
                ('type', models.PositiveSmallIntegerField(choices=[(0, 'цвет'), (1, 'размер'), (2, 'вариант'), (3, 'другое')], default=3, verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Свойство товара',
                'verbose_name_plural': 'Свойства товаров',
            },
        ),
        migrations.CreateModel(
            name='PropertyKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название ключа')),
            ],
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400, verbose_name='Название')),
                ('slug', models.SlugField(max_length=400, unique=True)),
                ('is_show', models.BooleanField(db_index=True, default=True, verbose_name='Показывать на сайте')),
            ],
            options={
                'verbose_name': 'Стиль',
                'verbose_name_plural': 'Стили',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='CatalogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата последнего обновления')),
                ('name', models.CharField(db_index=True, max_length=400, verbose_name='Название')),
                ('slug', models.SlugField(max_length=400, unique=True)),
                ('gender', models.IntegerField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Unisex')], db_index=True, verbose_name='Пол')),
                ('description', models.TextField(blank=True, max_length=1000, verbose_name='Описание')),
                ('article', models.CharField(max_length=30, verbose_name='Артикль')),
                ('score', models.IntegerField(db_index=True, default=0, verbose_name='Популярность')),
                ('store_address', models.CharField(max_length=250, verbose_name='Где забрать (адрес)')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.brand', verbose_name='Бренд')),
                ('properties', models.ManyToManyField(blank=True, related_name='items', to='shop.property', verbose_name='Свойства товара')),
                ('styles', models.ManyToManyField(related_name='items', to='shop.style')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата последнего обновления')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='shop.catalogitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Избранное',
                'verbose_name_plural': 'Избранное пользователей',
            },
        ),
        migrations.CreateModel(
            name='ItemSKU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата последнего обновления')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена')),
                ('discount', models.PositiveSmallIntegerField(default=0, verbose_name='Размер скидки в %')),
                ('available', models.BooleanField(default=True, verbose_name='В наличии')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skus', to='shop.catalogitem', verbose_name='Товар')),
                ('properties', models.ManyToManyField(blank=True, related_name='skus', to='shop.property', verbose_name='Свойства модели товара')),
            ],
            options={
                'verbose_name': 'Модель товара',
                'verbose_name_plural': 'Модели товаров',
            },
        ),
        migrations.CreateModel(
            name='ItemSKUImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата последнего обновления')),
                ('image', models.ImageField(blank=True, max_length=500, null=True, upload_to='images/')),
                ('item_sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.itemsku', verbose_name='Модель товара')),
            ],
            options={
                'verbose_name': 'Изображение товара',
                'verbose_name_plural': 'Изображения товаров',
            },
        ),
        migrations.AddField(
            model_name='property',
            name='key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.propertykey', verbose_name='Ключ'),
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата последнего обновления')),
                ('count', models.PositiveSmallIntegerField(default=1)),
                ('item_sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_carts', to='shop.itemsku')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_carts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзины пользователей',
            },
        ),
        migrations.CreateModel(
            name='LifeStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='lifestyles/')),
                ('description', models.TextField()),
                ('styles', models.ManyToManyField(related_name='lifestyles', to='shop.style')),
            ],
            options={
                'verbose_name': 'Образ',
                'verbose_name_plural': 'Образы',
            },
        ),
        migrations.CreateModel(
            name='UserLifeStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked', models.BooleanField(default=False)),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_lifestyles', to='shop.lifestyle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_lifestyles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_styles', to='shop.style')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_styles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('user', 'item'), name='unique_favorite'),
        ),
        migrations.AddConstraint(
            model_name='shoppingcart',
            constraint=models.UniqueConstraint(fields=('user', 'item_sku'), name='unique_shopping_cart'),
        ),
    ]
