# Generated by Django 5.0.6 on 2024-09-23 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(max_length=400, unique=True)),
                ('is_show', models.BooleanField(db_index=True, default=True, verbose_name='Показывать на сайте')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ('name',),
            },
        ),
        migrations.AlterField(
            model_name='style',
            name='name',
            field=models.CharField(max_length=400, unique=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='categories',
            field=models.ManyToManyField(related_name='items', to='shop.category'),
        ),
    ]
