# Generated by Django 5.0.6 on 2024-10-17 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_category_alter_style_name_catalogitem_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата последнего обновления')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, max_length=500, null=True, upload_to='images/')),
            ],
            options={
                'verbose_name': 'Изображение товара',
                'verbose_name_plural': 'Изображения товаров',
            },
        ),
        migrations.RemoveField(
            model_name='itemskuimage',
            name='item_sku',
        ),
        migrations.AddField(
            model_name='brand',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='main_image',
            field=models.ImageField(default='', upload_to='main_images/', verbose_name='Картинка в каталоге'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='propertykey',
            name='name',
            field=models.CharField(max_length=300, unique=True, verbose_name='Название ключа'),
        ),
        migrations.AddConstraint(
            model_name='property',
            constraint=models.UniqueConstraint(fields=('key', 'value', 'type'), name='unique_property'),
        ),
        migrations.AddConstraint(
            model_name='userlifestyle',
            constraint=models.UniqueConstraint(fields=('user', 'style'), name='unique_user_lifestyle'),
        ),
        migrations.AddField(
            model_name='brandsubscription',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='shop.brand'),
        ),
        migrations.AddField(
            model_name='brandsubscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brands', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='items', to='shop.image'),
        ),
        migrations.AddField(
            model_name='itemsku',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='skus', to='shop.image'),
        ),
        migrations.DeleteModel(
            name='ItemSKUImage',
        ),
        migrations.AddConstraint(
            model_name='brandsubscription',
            constraint=models.UniqueConstraint(fields=('user', 'brand'), name='unique_brand_subscription'),
        ),
    ]
