# Generated by Django 5.0.6 on 2024-10-31 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_brandsubscription_image_remove_itemskuimage_item_sku_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogitem',
            name='article',
            field=models.CharField(max_length=30, verbose_name='Артикул'),
        ),
    ]
