# Generated by Django 5.0.6 on 2024-11-04 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_catalogitem_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='style',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='style',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='styles/'),
        ),
    ]
