# Generated by Django 5.0.6 on 2024-11-07 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_style_description_style_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата последнего обновления')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'Магазин',
                'verbose_name_plural': 'Магазины',
            },
        ),
        migrations.RemoveField(
            model_name='lifestyle',
            name='styles',
        ),
        migrations.AddField(
            model_name='lifestyle',
            name='categories',
            field=models.ManyToManyField(related_name='lifestyles', to='shop.category'),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.shop', verbose_name='Магазин'),
        ),
    ]
