# Generated by Django 5.0.6 on 2024-11-07 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_shop_remove_lifestyle_styles_lifestyle_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogitem',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.shop', verbose_name='Магазин'),
        ),
    ]
