# Generated by Django 5.0.6 on 2024-11-15 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_catalogitem_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='booking_days',
            field=models.IntegerField(default=7, verbose_name='Кол-во дней для бронирования товара'),
        ),
    ]
