# Generated by Django 5.0.6 on 2024-11-07 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_shop_remove_lifestyle_styles_lifestyle_categories_and_more'),
        ('users', '0003_alter_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='shop',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.shop', verbose_name='Магазин'),
        ),
    ]
