# Generated by Django 5.0.6 on 2024-11-07 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_catalogitem_shop'),
        ('users', '0004_user_shop_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Администратор'), ('SHOP', 'Магазин'), ('USER', 'Пользователь'), ('MODERATOR', 'Модератор')], db_index=True, default='USER', max_length=20, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='user',
            name='shop',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='shop.shop', verbose_name='Магазин'),
        ),
    ]
